//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnByError {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Form1_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Form1_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearnByError.Form1.Resources", typeof(Form1_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane wejściowe.
        /// </summary>
        internal static string Dane_wejściowe {
            get {
                return ResourceManager.GetString("Dane_wejściowe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane z pliku: {0} nie zostały wczytane..
        /// </summary>
        internal static string Dane_z_pliku_0_nie_zostały_wczytane {
            get {
                return ResourceManager.GetString("Dane_z_pliku_0_nie_zostały_wczytane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane z pliku: {0} zostały wczytane..
        /// </summary>
        internal static string Dane_z_pliku_0_zostały_wczytane {
            get {
                return ResourceManager.GetString("Dane_z_pliku_0_zostały_wczytane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik nie został pobrany..
        /// </summary>
        internal static string Plik_nie_został_pobrany {
            get {
                return ResourceManager.GetString("Plik_nie_został_pobrany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik został pobrany..
        /// </summary>
        internal static string Plik_został_pobrany {
            get {
                return ResourceManager.GetString("Plik_został_pobrany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobieranie pliku z sieci....
        /// </summary>
        internal static string Pobieranie_pliku_z_sieci {
            get {
                return ResourceManager.GetString("Pobieranie_pliku_z_sieci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz dane wejściowe.
        /// </summary>
        internal static string Wybierz_dane_wejściowe {
            get {
                return ResourceManager.GetString("Wybierz_dane_wejściowe", resourceCulture);
            }
        }
    }
}
