/*
Author:  Marek Bar 33808
Contact: marekbar1985@gmail.com
Wyższa Szkoła Informatyki i Zarządzania w Rzeszowie
 */
using System;

namespace LearnByError.Database
{
    /// <summary>
    /// Patch class
    /// </summary>
    public class Patch
    {
        /// <summary>
        /// Patch table name
        /// </summary>
        public static String patchTable = SQL.General.Names.PatchTableName;

        /// <summary>
        /// Next patch number
        /// </summary>
        private static int patchNextNumber = 0;

        /// <summary>
        /// patch Number
        /// </summary>
        public int Number
        {
            get;
            private set;
        }

        /// <summary>
        /// Creates patch - number is autogenerated
        /// </summary>
        /// <param name="sql">your sql code</param>
        /// <param name="description">description - optional</param>
        public Patch(String sql = "", String description = "")
        {
            patchNextNumber++;
            Number = patchNextNumber;
            Sql = sql;
            Description = description;
        }

        /// <summary>
        /// Sql to execute
        /// </summary>
        public String Sql;

        /// <summary>
        /// Sql description
        /// </summary>
        public String Description;

        /// <summary>
        /// Executes patching sqls
        /// </summary>
        /// <returns></returns>
        public bool execute()
        {            
            if (Manager.Instance.Execute(Sql))
            {
                return Manager.Instance.Execute(String.Format(SQL.Patch.Insert, patchTable, Number, Description));
            }
            return false;
        }

        /// <summary>
        /// Checks if patch was executed
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public bool Exists(int id)
        {
            return (Manager.countIt(String.Format(SQL.Patch.Count,id)) > 0 ? true : false);
        }
    }
}//patch
